import React, { useState } from 'react';
import { X, Download, Printer, CheckCircle, ShieldCheck, Sparkles, Building2, Calendar, Hash } from 'lucide-react';
import { downloadPdfReport, printElement } from '../../utils/pdfGenerator';
import confetti from 'canvas-confetti';

export default function DigitalReportModal({ isOpen, onClose, reportData }) {
  const [isExporting, setIsExporting] = useState(false);

  if (!isOpen || !reportData) return null;

  const sampleId = reportData.sampleId || `SMP-${Date.now().toString().slice(-6)}`;
  const batchId = reportData.batchId || 'BATCH-2026-088';
  const dateTime = reportData.dateTime || new Date().toLocaleString('en-IN');
  const center = reportData.center || 'Lasalgaon Procurement Hub (Nashik)';
  const totalOnions = reportData.totalOnions || 200;
  const gradeA = reportData.gradeA || 72;
  const gradeB = reportData.gradeB || 18;
  const urs = reportData.urs || 10;
  const score = reportData.score || 87;
  const confidence = reportData.confidence || 94;
  const avgDiameter = reportData.avgDiameter || 68;
  const avgWeight = reportData.avgWeight || 82;

  const defects = reportData.defects || { damaged: 12, rotten: 5, sprouted: 3, undersized: 8 };

  const handleDownload = async () => {
    setIsExporting(true);
    // Trigger festive confetti celebrate!
    try {
      confetti({ particleCount: 80, spread: 70, origin: { y: 0.6 } });
    } catch (e) {}

    await downloadPdfReport('printable-report-card', `${sampleId}_Quality_Certificate.pdf`);
    setIsExporting(false);
  };

  const handlePrint = () => {
    printElement('printable-report-card');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-in fade-in overflow-y-auto">
      <div className="relative w-full max-w-3xl bg-white rounded-3xl shadow-2xl overflow-hidden border border-slate-200 my-8">
        
        {/* Modal Action Top Bar */}
        <div className="bg-slate-900 text-white px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-onion-600 flex items-center justify-center text-white text-base">
              🧅
            </div>
            <div>
              <h3 className="font-bold text-sm">Official Digital Quality Certificate</h3>
              <p className="text-[11px] text-slate-400">Generated by Computer Vision Engine</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-semibold transition-all"
            >
              <Printer className="w-4 h-4 text-amber-400" />
              Print
            </button>
            <button
              onClick={handleDownload}
              disabled={isExporting}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-gradient-to-r from-onion-700 to-onion-600 hover:from-onion-800 text-white text-xs font-bold shadow-md transition-all"
            >
              <Download className="w-4 h-4" />
              {isExporting ? 'Generating PDF...' : 'Download PDF Report'}
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* PRINTABLE CERTIFICATE AREA */}
        <div id="printable-report-card" className="p-8 bg-white space-y-6">
          
          {/* Certificate Header */}
          <div className="border-b-2 border-onion-700 pb-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-widest bg-onion-100 text-onion-800 rounded border border-onion-300">
                  AGRICULTURAL PROCUREMENT CERTIFICATE
                </span>
                <span className="text-xs font-bold text-emerald-600 flex items-center gap-1">
                  <CheckCircle className="w-3.5 h-3.5" /> AGMARK Compliant
                </span>
              </div>
              <h1 className="text-2xl font-black tracking-tight text-slate-900 mt-1">
                ONION QUALITY ASSESSMENT REPORT
              </h1>
              <p className="text-xs text-slate-500 font-medium">
                Automated Computer Vision & Defect Classification System
              </p>
            </div>

            <div className="text-left sm:text-right bg-slate-50 p-3 rounded-xl border border-slate-200 text-xs">
              <p className="font-extrabold text-slate-900 flex items-center gap-1 sm:justify-end">
                <Hash className="w-3.5 h-3.5 text-onion-600" />
                Sample ID: {sampleId}
              </p>
              <p className="text-slate-500 font-medium">{batchId}</p>
            </div>
          </div>

          {/* Metadata Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3.5 rounded-xl border border-slate-200 text-xs">
            <div>
              <span className="text-slate-400 font-medium block text-[10px]">DATE & TIME</span>
              <span className="font-bold text-slate-800 flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-slate-500" />
                {dateTime}
              </span>
            </div>
            <div>
              <span className="text-slate-400 font-medium block text-[10px]">PROCUREMENT HUB</span>
              <span className="font-bold text-slate-800 flex items-center gap-1 truncate">
                <Building2 className="w-3.5 h-3.5 text-slate-500" />
                {center}
              </span>
            </div>
            <div>
              <span className="text-slate-400 font-medium block text-[10px]">TOTAL ANALYZED</span>
              <span className="font-bold text-slate-800">{totalOnions} bulbs</span>
            </div>
            <div>
              <span className="text-slate-400 font-medium block text-[10px]">AI CONFIDENCE</span>
              <span className="font-bold text-emerald-700 flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                {confidence}%
              </span>
            </div>
          </div>

          {/* Main Quality Score Box */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            
            <div className="p-4 rounded-2xl bg-gradient-to-br from-onion-900 to-onion-800 text-white flex flex-col justify-between shadow-md">
              <span className="text-xs font-bold text-onion-200 uppercase tracking-wider">Overall Quality Score</span>
              <div className="flex items-baseline gap-2 my-2">
                <span className="text-5xl font-black">{score}</span>
                <span className="text-xl font-bold text-onion-300">/ 100</span>
              </div>
              <span className="text-[11px] font-semibold bg-white/20 px-2.5 py-1 rounded w-fit text-white">
                Grade: {score >= 85 ? 'Grade A (Export)' : score >= 70 ? 'Grade B (Standard)' : 'URS / Reject'}
              </span>
            </div>

            <div className="sm:col-span-2 p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Grade Composition breakdown</h4>
              
              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="p-2 rounded-xl bg-emerald-100/70 border border-emerald-300">
                  <span className="text-[10px] font-bold text-emerald-900 block">GRADE A</span>
                  <span className="text-xl font-black text-emerald-800">{gradeA}%</span>
                </div>

                <div className="p-2 rounded-xl bg-amber-100/70 border border-amber-300">
                  <span className="text-[10px] font-bold text-amber-900 block">GRADE B</span>
                  <span className="text-xl font-black text-amber-800">{gradeB}%</span>
                </div>

                <div className="p-2 rounded-xl bg-rose-100/70 border border-rose-300">
                  <span className="text-[10px] font-bold text-rose-900 block">URS (REJECT)</span>
                  <span className="text-xl font-black text-rose-800">{urs}%</span>
                </div>
              </div>

              <p className="text-[11px] text-slate-600 font-semibold bg-white p-2 rounded border border-slate-200">
                Bulb Physical Specs: Avg Diameter: <strong>{avgDiameter} mm</strong> • Avg Weight: <strong>{avgWeight} g</strong>
              </p>
            </div>

          </div>

          {/* Defect Percentages Table */}
          <div className="space-y-2">
            <h4 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider">
              Defect Classification Breakdown
            </h4>
            <table className="w-full text-xs text-left border border-slate-200 rounded-xl overflow-hidden">
              <thead className="bg-slate-100 text-slate-700 font-bold uppercase text-[10px]">
                <tr>
                  <th className="p-2.5">Defect Type</th>
                  <th className="p-2.5">Detected %</th>
                  <th className="p-2.5">Bulb Count</th>
                  <th className="p-2.5">Severity</th>
                  <th className="p-2.5">AGMARK Tolerance</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                <tr>
                  <td className="p-2.5 font-bold text-slate-800">Damaged (Skin Split / Cut)</td>
                  <td className="p-2.5 font-extrabold text-amber-600">{defects.damaged}%</td>
                  <td className="p-2.5 font-semibold">{Math.round((defects.damaged / 100) * totalOnions)} bulbs</td>
                  <td className="p-2.5"><span className="px-2 py-0.5 rounded bg-amber-100 text-amber-800 font-bold text-[10px]">Medium</span></td>
                  <td className="p-2.5 text-slate-500">Max 15%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-slate-800">Rotten (Neck Rot / Fungal)</td>
                  <td className="p-2.5 font-extrabold text-rose-600">{defects.rotten}%</td>
                  <td className="p-2.5 font-semibold">{Math.round((defects.rotten / 100) * totalOnions)} bulbs</td>
                  <td className="p-2.5"><span className="px-2 py-0.5 rounded bg-rose-100 text-rose-800 font-bold text-[10px]">High</span></td>
                  <td className="p-2.5 text-slate-500">Max 5%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-slate-800">Sprouted (Green Shoots)</td>
                  <td className="p-2.5 font-extrabold text-purple-600">{defects.sprouted}%</td>
                  <td className="p-2.5 font-semibold">{Math.round((defects.sprouted / 100) * totalOnions)} bulbs</td>
                  <td className="p-2.5"><span className="px-2 py-0.5 rounded bg-purple-100 text-purple-800 font-bold text-[10px]">Low</span></td>
                  <td className="p-2.5 text-slate-500">Max 8%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-slate-800">Undersized (&lt;45mm Bulb)</td>
                  <td className="p-2.5 font-extrabold text-blue-600">{defects.undersized}%</td>
                  <td className="p-2.5 font-semibold">{Math.round((defects.undersized / 100) * totalOnions)} bulbs</td>
                  <td className="p-2.5"><span className="px-2 py-0.5 rounded bg-blue-100 text-blue-800 font-bold text-[10px]">Medium</span></td>
                  <td className="p-2.5 text-slate-500">Max 10%</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Certificate Footer Stamp */}
          <div className="pt-4 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-4 text-[11px] text-slate-500">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
                ✓
              </div>
              <div>
                <p className="font-bold text-slate-800">Digital Seal & Verification Hash</p>
                <p className="font-mono text-[9px]">SHA256: 8f92a10b4c891e...912a</p>
              </div>
            </div>
            <div className="text-right">
              <p className="font-bold text-slate-800">OnionGrade AI Vision System</p>
              <p>Certified Procurement Mandi Inspector</p>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
